version: '3.7'

services:
  api:
    build: .
    container_name: 05-spring-security-basic
    hostname: 05-spring-security-basic
    image: richard-5
    restart: always
    networks:
      - db-postgres-network-4
    ports:
        - "9094:8080"
    command: ["java", "-jar", "/app/application.jar"]
    
networks:
  db-postgres-network-3:
    external:
        name: 02-spring-boot-postgresql-docker-compose_db-postgres-network